### PR TITLE
Ft refactor to mvvm 158790835

### PR DESCRIPTION
**Pull request by rbichage**
- Migrated to kotlin
- added mvvm 
-  display list of users 
-  view details of a single user 
-  share user profile

**How should this be manually tested?**

- clone this repo `$ git clone -b ft-refactor-to-mvvm-158790835 https://github.com/rbichage/github-users.git  `

- Open cloned directory `github-users` on Android Studio

- Build the project with gradle 

- Run the app in an emulator or any connected device

- The initial screen shows a list of users

- Navigate to user details by tapping on a single card.

- Share user profile

**What are the relevant pivotal tracker stories?**

[#158790835](https://www.pivotaltracker.com/story/show/158790835) 

**Screenshots**

device-2020-01-27-131002

### CODE REVIEW

**Review by leonardnjura — CHANGES_REQUESTED** [review]
Screenshot 2020-01-27 at 15 15 55
Good progress @rbichage 
Can we have one commit per PR as we discussed  🤔
Maintain the commit message for subsequent changes. You may edit it with the --edit flag. use the -f flag while pushing upstream as I demonstrated

**Comment by rbichage** [comment]
> Screenshot 2020-01-27 at 15 15 55
> 
> Good progress @rbichage Can we have one commit per PR as we discussed 🤔 Maintain the commit message for subsequent changes. You may edit it with the --edit flag. use the -f flag while pushing upstream as I demonstrated

@leonardnjura noted, on it.

**Comment by leonardnjura** [comment]
`
$ git add .
$ git commit --amend --no-edit
$ git push origin ft-example-branch -f
`

**Comment by leonardnjura** [comment]
Hey @rbichage,
Remember to add a READY label when you have one commit to be merged in per branch/PR. 
Also, ensure conflicts are resolved

**Pull request closed without merging**
